# Introduction

Data analysis is hard.

If you are going to be doing data analysis with criminological data it's likely that during your PhD/post-/undergraduate study you will receive some formal training in calculating descriptive statistics, statistical significance testing and probably some kind of statistical modelling. It's pretty likely that you may also have been on a training course to teach you how to apply a specific method to data (NCRM is great for these!)

I took courses like this when I was a student, and I teach on them now.

However, when I have been working with criminological data in practice there have been a lot of topics which have come up that weren't part of this formal curriculum. This is not to knock the formal curriculum - I don't teach these things either! But it is, I hope, useful to chart some of this extra-curricular terrain and to signpost areas which might benefit you in your data analysis.

So, this workshop will not teach you everything you need to know to be able to effectively fit statistical models to criminological data. I couldn't hope to do this anyway - criminology as a discipline is extremely varied (a rendes-vous subject, as some have said). So you might be a criminologist working on self-reported survey data about perceptions of fear and shame amongst young people, or you might be working with spatial data on coordinates of offences reported to the police, or analysing decades worth of convictions data for whole countries.

This also means that we will be skimming over the surface of quite a lot topics, rather than covering them in any great depth. As we go through I will signpost you to where you can find out more about each topic - books and books will have been written about each topic, so you can use this workshop as a jumping off point to dive further into topics that you find particularly useful.


### About you

I assume that you are familiar with the general linear model (although we will have a refresher) - my aim is not to cover things that you will find in a general undergraduate or postgrad methods course on statistical modelling, but focus on a set of illustratons of specific problems that can arise in some criminological contexts. I've tried to pick examples that are both specific enough to be illuminating, but general enough that the techniques I'll desribe (of say simulating quantities of interest from your fitted model) are generally relevant. No guarantees though. Hopefully act as inspiration when grappling with your own analytical problems.



## Types of criminological data

-   Surveys

-   Police

-   Courts // I'm sure there's more

-   What is the data provenance? What does this mean for my analysis?

-   Do I need survey weights? Do I need to account for interactions with officers that aren't recorded? Do I interpret convictions as a measure of offending?

## The general linear model

-   Big picture: two tribes of modellers?

    -   Economists versus epidemiologists

-   Won't include: mixed/multilevel/hierarchical/etc

-   But these might be relevant!

-   Focus on general linear model to think about binary and count outcomes

    -   Over-dispersion what to do?

-   inferential uncertainty versus outcome variability

## Measurement error and selection bias

-   Jose Pina Sanchez and measurement error

-   Walby and volatility over time

-   measurement error in general - from McElreath (can attenuate, but no guarantees)

-   measurement error in controls - uh oh

-   selection bias

    -   I guess I was thinking about the McElreath paper here/the Knox paper about conditioning on stop
    -   also Sander Greenland about everything is conditional on selection into the study (e.g. mortality in prison)
    -   And also can do the Sander Greenland stuff on probabilistic bias analysis

## Using models to describe quantities of interest

-   Gary King and general principle

-   secondary motivation of what is your estimand?

-   general principle of adjusted predictive comparisons (and also g-estimation)

-   specific example of victimization divides as a DQI

## Ethics of working with criminological data

-   Jessica Simes and community loss

-   
